name: gnr8
description: Regenerative Networks.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_launcher: ^2.1.0
  google_fonts: ^4.0.3
  google_maps: ^6.2.0
  animated_bottom_navigation_bar: ^1.2.0
  font_awesome_flutter: ^10.4.0
  location: ^4.4.0
  custom_info_window: ^1.0.1
  url_launcher: ^6.1.10
  flutter_web3: ^2.1.9
  fl_chart: ^0.61.0
  get: ^4.6.5
  google_mlkit_object_detection: ^0.6.0
  video_player: ^2.6.0
  chewie: ^1.4.0
  image_picker: ^0.8.7
  rflutter_alert: ^2.0.4
  walletconnect_dart: ^0.0.11
  pinch_zoom: ^1.0.0
  chatview: ^1.2.1
  web3dart: ^2.5.1
  flutter_native_splash: ^2.2.19
  firebase_core: ^2.8.0
  #flutter_geofire: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "icon/appIcon.png"
  platforms:
    android:
      enable: true
      image_path: "icon/appIcon.png"
      #adaptive_background_color: '#000000'
      adaptive_background_image: "icon/ic_background.png"
      adaptive_foreground_image: "icon/ic_foreground.png"
      #adaptive_round_image: "assets/ic_logo_round.png"
      adaptive_monochrome_image: "icon/ic_foreground.png"
    ios:
      enable: false
      image_path: "icon/appIcon.png"
   

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/  

  
