name: gnr8
description: Regenerative Networks.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_launcher: ^2.1.0
  google_fonts: ^4.0.3
  google_maps: ^6.2.0
  animated_bottom_navigation_bar: ^1.1.0+1
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.7.0
  location: ^4.4.0
  google_maps_flutter: ^2.2.4
  custom_info_window: ^1.0.1
  url_launcher: ^6.1.10
  #flutter_geofire: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "icon/appIcon.png"
  platforms:
    android:
      enable: true
      image_path: "icon/appIcon.png"
      # adaptive_background_color: '#ffffff'
      # adaptive_background_image: "assets/ic_background.png"
      # adaptive_foreground_image: "assets/ic_foreground.png"
      #adaptive_round_image: "assets/ic_logo_round.png"
      #adaptive_monochrome_image: "assets/ic_logo_monochrome.png"
    ios:
      enable: true
      image_path: "icon/appIcon.png"
   

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/  

  
